name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Elastic Beanstalk CLI
      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade --user
          export PATH=$PATH:$HOME/.local/bin
          eb --version # Verify installation

      # Step 5: Check and create Elastic Beanstalk environment if missing
      - name: Check Elastic Beanstalk Environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          # Initialize the Elastic Beanstalk application
          eb init -p node.js aketist-social-network --region $AWS_REGION

          # Check if the environment exists
          if ! eb status aketist-social-network-env; then
            echo "Environment does not exist. Creating a new environment..."

            # Create the environment with your VPC and Subnet IDs
            eb create aketist-social-network-env \
              --region $AWS_REGION \
              --platform "node.js" \
              --instance_type "t2.micro" \
              --vpc.id vpc-0d1868b4b90d007a9 \
              --vpc.subnets subnet-01c64115c12128761 \
              --vpc.publicip \
              --envvars "NODE_ENV=production"
          else
            echo "Environment exists. Proceeding with deployment."
          fi

      # Step 6: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          eb use aketist-social-network-env
          eb deploy
