name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests (optional but recommended)
      - name: Run tests
        run: |
          if [ -f package.json ]; then
            npm test || echo "No tests defined, skipping test step."
          fi

      # 5. Install Elastic Beanstalk CLI
      - name: Install Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade --user
          export PATH=$PATH:$HOME/.local/bin
          eb --version # Verify installation

      # 6. Check and Create Elastic Beanstalk Environment
      - name: Initialize Elastic Beanstalk Environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          # Initialize the Elastic Beanstalk application
          eb init -p node.js aketist-social-network --region $AWS_REGION

          # Check if the environment exists
          if eb status --verbose | grep -q "No environment found for application"; then
            echo "Environment does not exist. Creating a new environment..."
            eb create aketist-social-network-env --region $AWS_REGION --platform node.js
          else
            echo "Environment exists. Proceeding with deployment..."
          fi

      # 7. Deploy to AWS Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          eb use aketist-social-network-env
          eb deploy